### ISSUE TITLE
Refactor the repo files structure

### ISSUE THREAD

**Issue by mehdy** [OSS-Hackathon/IranOpenSourceHackathon#14]
Generate the repo URL and its name from the fs structure instead of explicit fields.

**Comment by loreanvictor** [comment]
but more importantly: distinguish maintainer and owner. I guess thats a pretty important distinction, and we should also make sure the same distinction is reflected in the table in README.

also also: clarify [this section](https://github.com/OSS-Hackathon/IranOpenSourceHackathon#i-am-a-maintainer-can-i-add-my-repos-to-this-hackathon) accordingly, since it is vague on maintainer / owner right now.

**Comment by loreanvictor** [comment]
@mehdy I actually created a [PR](https://github.com/OSS-Hackathon/IranOpenSourceHackathon/pull/17) for this issue. It resolves the aforementioned problems, also it automatically updates the README file instead of printing the generated table. You can checkout [this guideline](https://github.com/OSS-Hackathon/IranOpenSourceHackathon/tree/refactored-repo-structure/scripts) on how to run the new script and test it out.
