### ISSUE TITLE
Improvements on process of submitting repos

### ISSUE THREAD

**Issue by loreanvictor** [OSS-Hackathon/IranOpenSourceHackathon#6]
- Add a guideline on how to submit new repos
- Add a guideline for running the table generation script locally (dependencies, arguments, etc)
- Improvements to structure of the YAML files:
  - Repo owner **MUST** match the name of the folder, so there is no need for including it in the YAML file.
  - Repository **MUST** match the name of the file, so the link to it can be deduced automatically as well.
  - Languages can be read from GitHub itself ([example](https://api.github.com/repos/mehdy/pyeez/languages)). I am not sure what would be the best way of incorporating this though since also caching this info and not spamming GitHub API would be nice.

**Comment by loreanvictor** [comment]
@mehdy

**Comment by mehdy** [comment]
ETA: Apr 11

**Comment by mehdy** [comment]
1. has been resolved.
2. We'll follow this one through #13 
3.1 I put the owner field for some cases like the [Keepalived-Exporter](https://github.com/cafebazaar/keepalived-exporter) where the repository is located in Cafebazaar Org, and I am the maintainer of the project. Maybe rename it to `maintainer` and making it optional that making the default value the repo's user/org owner?
3.2 The repo name and URL can be generated from the structure. Opened #14  to refactor this.
3.3 I still prefer to get the languages from the person who entered the repo because sometimes the repo contains some files that make a for example python-based project into an HTML-based project.

**Comment by loreanvictor** [comment]
yep agree with all points. should we close this issue?

**Comment by mehdy** [comment]
@loreanvictor Sure!
